### ISSUE TITLE
No examples anywhere

### ISSUE THREAD

**Issue by mlmarius** [antelopeusersgroup/antelope_contrib#102]
Hi. I have been searching high and low for some documentation or examples but after days of frustration I have nothing. I have 2 usecases which I would like to implement in Python

1) open an antelope database and list all events available in there. What if i do some filtering on the events ?
2) open an antelope database, join with origins and other tables, do some filtering, list all results

The examples I was able to find do not work: `http://www.brtt.com/events/papagayo2013/talks/2013_Guanacaste_CR_SimpleAntelopeProgramming.pdf`

it says that Dbptr has no attribute nrecs() ?!?

I am on Antelope 5.7

Can anybody provide some gists that will enable me to do the above tasks ?
If not possible atleast can someone show me how to do this with the command line tools ?

**Comment by jeakins** [comment]
You might review one of the pre-existing python scripts in contrib such as db2kml_py.  It uses datascope.dbopen along with db_pointer functions and then loops over the records of the views it creates.  Using this as a template, you should be able to write something to do what you want.  

I will leave it to the python pros to go into more details.   

--Jennifer
